### ISSUE TITLE
outjoin.exe не найден

### ISSUE THREAD

**Issue by ghost** [dot3v1L/Joiner#1]
при скрещивании вообще всех exe что я тестил выдаёт ошибку
![6jN0BQnY3q](https://user-images.githubusercontent.com/75296588/100704863-0ed13700-33c8-11eb-9aad-641dae5ceaf0.png)
затем выдаёт вот это и крашит/окирпичивается
![Joiner_FJWalpMIrc](https://user-images.githubusercontent.com/75296588/100704921-2ad4d880-33c8-11eb-9ac4-418f91e40eff.png)

**Comment by 0x0f0c** [comment]
смог исправить?

**Comment by hinqiwame** [comment]
> смог исправить?

раз ошибку закрыл значит смог наверное

**Comment by ghost** [comment]
> смог исправить?

нет вроде, давно было, закрыл потому что не дождался ответа, скорее всего кодер забросил проект
